### ISSUE TITLE
Modification prix + offre

### ISSUE THREAD

**Issue by AEFerrets** [Mastersnes/AEFerrets#10]
Bonjour,
Je souhaiterais modifier le prix de mes marque-pages qui coûtent désormais 3€, ainsi que proposer une offre commerciale à mes acheteurs qui est : 1 marque-pages offert pour 2 livres achetés.
Ayant fait un salon hier et attendant un acheteur pour un marque-page de Séraphin, j'aurais besoin, si possible, de cette modification assez rapidement :) 

Merci beaucoup et bonne journée à vous :)

**Comment by Mastersnes** [comment]
Bonjour,
Nous avons bien pris en compte votre demande.
Concernant le prix de 3€ pour les marques pages, cette demande est déjà en ligne.
Pour l'avenir, il vous suffira de modifier le fichier marquesPage.json afin de modifier le prix et de recharger le site via l'option d'administration. N’hésitez pas à revenir vers nous au besoin.

Concernant l'offre commerciale, j'aimerai vous offrir une possibilité de créer vous même vos offres commerciales via un fichier json en plus. Cette possibilité est en étude.
En attendant, j'ajoute en dur l'offre commerciale demandé dans le code et relivre dés que possible.

Merci de votre confiance.
Cordialement,
Applines

**Comment by Mastersnes** [comment]
Livraison effectué =)
