### ISSUE TITLE
Suppression de bouton

### ISSUE THREAD

**Issue by AEFerrets** [Mastersnes/AEFerrets#11]
Bonjour,

Suite à la fermeture de ma page Patreon, j'aimerais supprimer le bouton Patreon de mon site.

Merci beaucoup et bon courage.

A.E Ferrets
PS: le bouton en question: 
![patreon](https://user-images.githubusercontent.com/32059957/31222098-2f11aaf2-a9c6-11e7-9409-6e91e49baf60.png)

**Comment by Mastersnes** [comment]
Bonjour =)
Cette demande a été prise en compte et sera livré très prochainement.
Merci pour votre confiance.
Cordialement,
Applines
