### ISSUE TITLE
Modification de bouton

### ISSUE THREAD

**Issue by AEFerrets** [Mastersnes/AEFerrets#13]
Bonjour,
Serait-il possible de modifier le bouton "Exemplaire dédicacé" par " Acheter à l'auteure" ou "Acheter auprès de l'auteure" ou quelque chose du genre, s'il vous plaît ? Car les gens pense qu'il n'est possible que de commander un exemplaire dédicacé ... 

Merci monsieur le développeur ! ^^

**Comment by Mastersnes** [comment]
Bonjour dame Ferrets =)
Nous prenons en compte votre demande !
Merci de la confiance que vous nous portez ^^

**Comment by Mastersnes** [comment]
Voilà =) emballé c'est livré !
