### ISSUE TITLE
Modifications site

### ISSUE THREAD

**Issue by AEFerrets** [Mastersnes/AEFerrets#14]
Bonjour,
Suite à quelques retours, je souhaiterai effectuer les modification suivante sur mon site :

-> Mettre en rouge et en gras l'astérisque précisant que LPP DYS est une version DYS
-> Demander de choisir le marque page offert. Par exemple : Merci de bien vouloir choisir un marque-page  (offert)
-> Si la case dédicace est laissé vide, rien ne m'indique dans le mail que la personne veut une dédicace à son prénom.
-> Afficher quelque chose qui pourrait m'indiquer de quel marque-page il s'agit.  ^^" Car j'ai les nom, mais difficile de me souvenir duquel il s'agit (quand, par exemple, ils y a plusieurs fées ^^)

Merci :)

**Comment by Mastersnes** [comment]
Bonjour !
Je m'en occupe =)
Concernant le premier point il est déjà en ligne, j'ai également remis LPP classique en tete d'affiche pour que les gens ne se trompe plus ^^

**Comment by Mastersnes** [comment]
Second point corrigé.
Si l'utilisateur n'a pas encore choisi ses marque-pages gratuit un message d'alerte lui demandera de valider son choix ou d'aller choisir ses marque-pages.

**Comment by Mastersnes** [comment]
Troisième point corrigé.

**Comment by Mastersnes** [comment]
Voilà tout est terminé =)
Avec plaisir o/
