### ISSUE TITLE
Ajout - Informations

### ISSUE THREAD

**Issue by AEFerrets** [Mastersnes/AEFerrets#15]
Bonjour,

Je souhaiterais apporter les améliorations suivante à mon site. Serait-ce possible ?

J'aimerais ajouter, sur la page de chaque livre, les informations le concernant.

- Date de sortie
- ISBN
- Nombre de page
- Format (ou dimension)
- Langue
- Prix

Merci :)

**Comment by Mastersnes** [comment]
Done =)
Have fun o/
