### ISSUE TITLE
Bouton Patreon

### ISSUE THREAD

**Issue by AEFerrets** [Mastersnes/AEFerrets#8]
Bonjour,
Je souhaiterais ajouter à mon site le bouton vers ma page Patreon :) Je vous joins l'image ainsi que le lien vers ma page :)
https://www.patreon.com/aeferrets

![patreon](https://user-images.githubusercontent.com/32059957/30535914-2f1f2b92-9c64-11e7-929a-6eccf58cdd2d.png)

Merci beaucoup :) Et bon courage !

**Comment by Mastersnes** [comment]
Modification apportée, la livraison aura lieu ce soir.
Cordialement
